SELECT distinct
T2.CONSTRAINT_TYPE,
T1.CONSTRAINT_NAME,
T1.TABLE_SCHEMA, 
T1.TABLE_NAME,
T1.COLUMN_NAME,
T1.REFERENCED_TABLE_SCHEMA, 
T1.REFERENCED_TABLE_NAME, 
T1.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE T1
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS T2 ON T1.TABLE_SCHEMA = T2.TABLE_SCHEMA AND T1.TABLE_NAME = T2.TABLE_NAME 
INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS T3 ON  T1.CONSTRAINT_NAME = T3.CONSTRAINT_NAME
WHERE T2.CONSTRAINT_TYPE = 'FOREIGN KEY'
AND T1.TABLE_SCHEMA = 'person'
AND T1.TABLE_NAME = 'tb_person'


