version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=David@Mssql1
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED = 1
    volumes:
      - type: bind
        source: /c/temp/mssql22/data/
        target: /var/opt/mssql/data/
    container_name: mssql22