version: '3'

services:
  php:
      build: .
      container_name: php
      ports:
        - '80:80'
      volumes:
        - ./html:/var/www/html
      depends_on:
        - db
      links:
        - db  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"      
    volumes:
      - type: bind
        source: /c/temp/postgres/pgsql15
        target: /var/lib/data/
    container_name: postgres15