version: '3'

services:
  php:
      build: .
      container_name: php
      ports:
        - '80:80'
      volumes:
        - ./ui:/var/www/html
      depends_on:
        - db
      links:
        - db  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"      

    container_name: postgres15