SET GLOBAL event_scheduler = ON;
SHOW PROCESSLIST;
SHOW EVENTS;

DROP EVENT IF EXISTS EV_1;

DELIMITER |
CREATE EVENT EV_1
    ON SCHEDULE EVERY 1 MINUTE
    STARTS '2022-11-29 07:40:00'
    DO
      BEGIN
        INSERT INTO TB_1 (ID) VALUES (1);
      END |
DELIMITER ;

